language: python
python:
  - "3.5"
  - "3.6"
install:
  pip install -r dev-requirements.txt;
script:
  - flake8 .
  - coverage run manage.py test --settings=mprjlabeler.test_settings
after_success:
  - codecov 
notifications:
  email:
    - rhenan.ferreira@mprj.mp.br
    - felipe.gomes.ferreira@gmail.com
