version: '2'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:9.5.3'
    expose:
      - 5432
    volumes:
      - postgresdata:/var/lib/postgresql/data/

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    expose:
      - 6379
    volumes:
      - redisdata:/data

  lighttpd:
    container_name: 'lighttpd'
    image: 'sebp/lighttpd'
    ports:
      - '0.0.0.0:8081:80'
    volumes:
      - media:/var/www/localhost/htdocs/media/
      - static:/var/www/localhost/htdocs/static/
    depends_on:
      - web
    tty: true

  web:
    build: '.'
    image: 'websource'
    command: 'python manage.py runserver 0.0.0.0:8080'
    ports:
      - '0.0.0.0:8080:8080'
    volumes:
      - media:/media
      - static:/static
      - ./:/app
    depends_on:
      - postgres
      - redis

  celery_worker:
    image: 'websource'
    command: './app.sh'
    environment:
      WORKER: 1 
    volumes_from:
      - web
    depends_on:
      - web

  code:
    image: 'codercom/code-server'
    env_file:
      - code.env
    ports:
      - '0.0.0.0:8082:8080'
    volumes:
      - ./:/home/coder/project/


volumes:
  postgresdata:
  redisdata:
  media:
  static:
